export const SITE = {
  name: "Rank Advertising",
  email: "hello@rankadvertising.co",
  phone: "+91 93722 14451",
  address:
    "4th Floor, Akshar Blue Chip IT Park, Turbhe MIDC, Turbhe, Navi Mumbai, Maharashtra 400703",
};

export type ServiceCategory = {
  slug: string;
  title: string;
  tagline: string;
  items: string[];
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    slug: "zoho",
    title: "Zoho Services",
    tagline: "Certified Zoho implementation, customization & support.",
    items: [
      "Zoho CRM",
      "Zoho Implementation",
      "Zoho Creator Services",
      "Zoho Consulting Services",
      "Zoho One Implementation",
      "Zoho Implementation Audit",
      "Zoho Support",
      "Hire Zoho Developer",
    ],
  },
  {
    slug: "seo",
    title: "Core Digital Marketing",
    tagline: "Rank higher. Get found. Drive traffic that converts.",
    items: [
      "Search Engine Optimization (SEO)",
      "AI SEO & AI Citation Optimization",
      "Technical SEO",
      "Local SEO",
      "Content SEO",
      "Organic Traffic Growth Strategy",
    ],
  },
  {
    slug: "website",
    title: "Website Services",
    tagline: "Fast, conversion-focused websites engineered to perform.",
    items: [
      "Website Design",
      "Website Development",
      "Conversion-Focused Website Development",
      "Landing Page Development",
      "Website Maintenance",
      "Technical Website Fixes",
      "Responsive Website Design",
    ],
  },
  {
    slug: "performance",
    title: "Performance Marketing",
    tagline: "Predictable pipeline. Measurable ROI. Profitable growth.",
    items: [
      "Performance Marketing",
      "Lead Generation Campaigns",
      "Conversion Optimization",
      "ROI-Focused Advertising",
      "Customer Acquisition Campaigns",
      "Campaign Scaling & Optimization",
    ],
  },
  {
    slug: "ads",
    title: "Paid Advertising",
    tagline: "Google, Meta, LinkedIn — managed by certified specialists.",
    items: [
      "Google Ads Management",
      "Meta Ads (Facebook & Instagram)",
      "LinkedIn Ads",
      "PPC (Pay-Per-Click) Advertising",
      "Retargeting Campaigns",
      "Lead Generation Ads",
      "Brand Awareness Campaigns",
    ],
  },
  {
    slug: "social",
    title: "Social Media Marketing",
    tagline: "Build the audience. Grow the brand. Spark the conversation.",
    items: [
      "Instagram Marketing",
      "Facebook Marketing",
      "LinkedIn Marketing",
      "Social Media Management",
      "Social Media Strategy",
      "Reels Creation",
      "Content Calendar Planning",
      "Community Engagement",
      "Influencer Marketing",
      "Social Media Growth Campaigns",
    ],
  },
  {
    slug: "branding",
    title: "Content & Branding",
    tagline: "Distinctive brands. Stories that travel. Content that lasts.",
    items: [
      "Content Marketing",
      "LinkedIn Personal Branding",
      "Thought Leadership Marketing",
      "Brand Identity Development",
      "Branding Campaigns",
      "Creative Design",
      "Visual Branding",
    ],
  },
  {
    slug: "email",
    title: "Email Marketing",
    tagline: "Nurture leads, retain customers, drive repeat revenue.",
    items: [
      "Email Marketing Campaigns",
      "Email Automation",
      "Promotional Email Campaigns",
      "Customer Engagement Emails",
    ],
  },
  {
    slug: "extras",
    title: "Additional Services",
    tagline: "Strategy, research & consulting to power your next phase.",
    items: [
      "SEM (Search Engine Marketing)",
      "Online Reputation Management (ORM)",
      "Brand Strategy",
      "Market Research",
      "Digital Transformation Consulting",
      "Business Growth Consulting",
    ],
  },
];

export const INDUSTRIES: { name: string; description: string }[] = [
  { name: "Legal", description: "Client acquisition for law firms and legal consultants." },
  { name: "Healthcare", description: "Patient growth for clinics, hospitals & wellness brands." },
  { name: "Hospitality", description: "Bookings & brand love for hotels, restaurants & resorts." },
  { name: "E-commerce", description: "Scaling D2C brands with paid, SEO and retention loops." },
  { name: "SaaS", description: "Pipeline, MQLs and product-led growth for software companies." },
  { name: "Real Estate", description: "Qualified buyer & investor leads at scale." },
  { name: "B2B", description: "Account-based marketing & enterprise lead generation." },
  { name: "Manufacturing", description: "Distributor, dealer & export lead generation." },
  { name: "Education / EdTech", description: "Enrolment growth and lifecycle marketing." },
];

export const COUNTRIES = [
  "India",
  "USA",
  "Canada",
  "Australia",
  "UAE",
  "UK",
  "Singapore",
  "Germany",
  "Saudi Arabia",
  "Netherlands",
];

// ---------- Service detail pages ----------
export type ServiceDetail = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  tagline: string;
  intro: string;
  highlights: string[];
};

function s(
  slug: string,
  name: string,
  category: string,
  categorySlug: string,
  tagline: string,
  intro: string,
  highlights: string[],
): ServiceDetail {
  return { slug, name, category, categorySlug, tagline, intro, highlights };
}

export const SERVICE_DETAILS: ServiceDetail[] = [
  // Zoho
  s("zoho-crm", "Zoho CRM", "Zoho Services", "zoho",
    "Sell smarter with a CRM tuned to how your team actually works.",
    "We design, customize and roll out Zoho CRM so your sales team has clean pipelines, automated follow-ups and real-time reporting — without the bloat. From lead capture to deal closure, every stage is mapped to your process.",
    ["Pipeline & stage automation", "Lead scoring & assignment rules", "Email, call & WhatsApp integration", "Dashboards your sales head will actually use", "Training & adoption support"]),
  s("zoho-implementation", "Zoho Implementation", "Zoho Services", "zoho",
    "End-to-end Zoho rollouts done right, the first time.",
    "Our certified consultants handle requirement mapping, configuration, data migration, integrations and team enablement. We've implemented Zoho across services, manufacturing, real estate and SaaS businesses globally.",
    ["Business process discovery", "Module configuration & workflows", "Clean data migration", "Third-party integrations", "Go-live support & hand-holding"]),
  s("zoho-creator-services", "Zoho Creator Services", "Zoho Services", "zoho",
    "Custom low-code apps built on Zoho Creator.",
    "When off-the-shelf doesn't cut it, we build custom internal tools, portals and field apps on Zoho Creator — fast, scalable and tightly integrated with the rest of your Zoho stack.",
    ["Custom app design & build", "Mobile-ready interfaces", "Deluge scripting & automation", "REST API & external integrations", "Ongoing enhancement support"]),
  s("zoho-consulting-services", "Zoho Consulting Services", "Zoho Services", "zoho",
    "Strategy & roadmap from people who've done it 100+ times.",
    "Whether you're picking your first Zoho module or untangling a sprawling Zoho One setup, our consultants help you design the right architecture, automations and reporting layer for your business.",
    ["Zoho product fit assessment", "Architecture & integration design", "Process & automation blueprints", "License optimization", "Implementation roadmap"]),
  s("zoho-one-implementation", "Zoho One Implementation", "Zoho Services", "zoho",
    "Run your entire business on one connected operating system.",
    "We deploy Zoho One — CRM, Books, People, Desk, Projects, Campaigns and more — as one connected workspace. Departments stop emailing spreadsheets and start working off the same data.",
    ["Cross-module data flow design", "Finance, HR, Sales & Support setup", "Unified dashboards", "Role-based access & security", "Phased rollout plan"]),
  s("zoho-implementation-audit", "Zoho Implementation Audit", "Zoho Services", "zoho",
    "Find out exactly what's broken in your current Zoho setup.",
    "We audit your existing Zoho configuration, workflows, data hygiene and integrations, then deliver a prioritized action plan to fix gaps, reduce manual work and unlock the value you've already paid for.",
    ["Configuration & workflow review", "Data quality & duplication audit", "Integration health-check", "Adoption & training gaps", "Prioritized fix roadmap"]),
  s("zoho-support", "Zoho Support", "Zoho Services", "zoho",
    "On-demand Zoho experts on a monthly retainer.",
    "Skip the in-house hire. Our support pods handle daily Zoho admin, enhancements, automations and user queries on a predictable monthly plan — so your team stays productive.",
    ["Dedicated Zoho admin time", "Bug fixes & enhancements", "New workflow & report builds", "User training & helpdesk", "Quarterly health reviews"]),
  s("hire-zoho-developer", "Hire Zoho Developer", "Zoho Services", "zoho",
    "Plug certified Zoho developers into your team this week.",
    "Hire pre-vetted Zoho developers — full-time, part-time or project-based — to work alongside your team. Deluge, Creator, integrations, CRM customisation — covered.",
    ["Pre-vetted certified developers", "Flexible engagement models", "Time-zone aligned to you", "Transparent reporting", "Replacement guarantee"]),

  // SEO
  s("seo", "Search Engine Optimization (SEO)", "Core Digital Marketing", "seo",
    "Compounding organic growth, built on technical fundamentals.",
    "We build SEO programs that move real KPIs — qualified traffic, leads and revenue. Our team combines technical SEO, content strategy and authority building into a roadmap with monthly accountability.",
    ["Keyword & competitor research", "On-page & technical optimization", "Content production & optimization", "Authority & link acquisition", "Transparent monthly reporting"]),
  s("ai-seo", "AI SEO & AI Citation Optimization", "Core Digital Marketing", "seo",
    "Get cited by ChatGPT, Gemini, Perplexity and Google AI Overviews.",
    "Search is shifting from blue links to AI answers. We optimize your brand, content and structured data so AI engines cite you as the source — not your competitor.",
    ["AI Overviews & AI Mode optimization", "ChatGPT / Perplexity / Gemini citations", "Entity & structured data work", "Answer-ready content production", "AI visibility tracking"]),
  s("technical-seo", "Technical SEO", "Core Digital Marketing", "seo",
    "Fix the foundation before you scale the content.",
    "Crawl, render, index, schema, Core Web Vitals — we cover the unglamorous work that quietly unlocks rankings. Perfect for sites that have plateaued despite good content.",
    ["Full technical audit", "Crawl & index management", "Site speed & Core Web Vitals", "Schema & structured data", "Migration & redirect planning"]),
  s("local-seo", "Local SEO", "Core Digital Marketing", "seo",
    "Own the map pack in every city you serve.",
    "From Google Business Profile to local citations, reviews and city-page architecture, we help multi-location and service-area businesses dominate local results.",
    ["Google Business Profile optimization", "Local citation building", "Review acquisition strategy", "Location landing pages", "Local rank tracking"]),
  s("content-seo", "Content SEO", "Core Digital Marketing", "seo",
    "Topical authority built one well-researched page at a time.",
    "We plan, write and optimize content clusters that actually rank — informed by search intent, competitor gaps and your sales conversations.",
    ["Topic cluster planning", "SERP-driven briefs", "Expert content production", "On-page optimization", "Content refresh & pruning"]),
  s("organic-traffic-growth-strategy", "Organic Traffic Growth Strategy", "Core Digital Marketing", "seo",
    "A 12-month roadmap to predictable organic growth.",
    "We diagnose what's holding your organic channel back and ship a quarterly roadmap with clear ownership, KPIs and forecasts — built for in-house teams or co-delivery.",
    ["Channel & competitor diagnostic", "12-month growth roadmap", "Quarterly OKRs & forecasts", "Resourcing & workflow design", "Executive reporting"]),

  // Website
  s("website-design", "Website Design", "Website Services", "website",
    "Beautiful, brand-led design that converts attention into action.",
    "We design websites that look premium and perform — clean visual systems, persuasive layouts and accessible UI, all rooted in your brand and your buyer's journey.",
    ["Brand & UX discovery", "Wireframes & prototypes", "High-fidelity design system", "Accessibility & responsive design", "Conversion-first layouts"]),
  s("website-development", "Website Development", "Website Services", "website",
    "Production-grade builds on the stack that fits your goals.",
    "WordPress, Webflow, Shopify or fully custom React — we build fast, secure, SEO-ready websites engineered for the long haul.",
    ["Stack recommendation", "Performance-first builds", "CMS & component libraries", "Integrations & APIs", "Hand-off & training"]),
  s("conversion-focused-website-development", "Conversion-Focused Website Development", "Website Services", "website",
    "Websites measured by what they convert, not how they look.",
    "Every section is mapped to a buyer question. Every CTA is tracked. We build sites with conversion baked in — then keep optimising post-launch.",
    ["Message & offer mapping", "Conversion architecture", "Tracking & analytics setup", "A/B test plan", "Post-launch CRO sprints"]),
  s("landing-page-development", "Landing Page Development", "Website Services", "website",
    "Campaign landing pages that punch above their cost-per-click.",
    "Purpose-built landing pages for your paid campaigns — fast, focused and built around a single conversion goal, with proper tracking out of the box.",
    ["Offer & message clarity", "Fast, mobile-first builds", "Form & funnel tracking", "A/B testing ready", "CRM & ad platform sync"]),
  s("website-maintenance", "Website Maintenance", "Website Services", "website",
    "Keep your site fast, secure and bug-free — on a predictable plan.",
    "Updates, backups, security patches, content tweaks, performance monitoring — handled by a senior team on a monthly retainer so you can focus on your business.",
    ["Core & plugin updates", "Security & backup management", "Uptime & performance monitoring", "Content & design updates", "Monthly health reports"]),
  s("technical-website-fixes", "Technical Website Fixes", "Website Services", "website",
    "Stop firefighting. Hand the broken bits to specialists.",
    "Page speed regressions, broken integrations, cumbersome layouts, SEO-tank migrations — we step in, diagnose and fix, fast.",
    ["Rapid technical diagnostics", "Page speed remediation", "Integration & API repair", "SEO & migration recovery", "Senior engineer access"]),
  s("responsive-website-design", "Responsive Website Design", "Website Services", "website",
    "Pixel-perfect experiences from 320px to 4K.",
    "Mobile-first by default. We design and build sites that feel native across every device — without compromising performance or accessibility.",
    ["Mobile-first design system", "Adaptive layouts", "Touch-friendly UX", "Cross-browser QA", "Real-device performance testing"]),

  // Performance
  s("performance-marketing", "Performance Marketing", "Performance Marketing", "performance",
    "Predictable growth driven by data, not gut feel.",
    "Full-funnel performance marketing across paid search, social and programmatic — managed with daily rigour and weekly reporting tied to your pipeline KPIs.",
    ["Channel strategy & forecasting", "Daily campaign management", "Creative & landing page testing", "Attribution & analytics", "Weekly KPI reviews"]),
  s("lead-generation-campaigns", "Lead Generation Campaigns", "Performance Marketing", "performance",
    "Fill your pipeline with qualified, sales-ready leads.",
    "We design end-to-end lead-gen engines — offer, audience, ad, landing page, follow-up — built for cost-per-qualified-lead, not vanity metrics.",
    ["Offer & ICP definition", "Channel & creative testing", "Form & qualification flows", "CRM & nurture integration", "Lead-to-revenue reporting"]),
  s("conversion-optimization", "Conversion Optimization", "Performance Marketing", "performance",
    "Squeeze more revenue from the traffic you already have.",
    "Structured CRO sprints — research, hypothesis, test, learn — that compound month over month into real revenue lifts.",
    ["Heuristic & analytics audit", "User research & heatmaps", "A/B & multivariate testing", "Funnel & checkout optimization", "Quarterly insight reports"]),
  s("roi-focused-advertising", "ROI-Focused Advertising", "Performance Marketing", "performance",
    "Every rupee, dollar and dirham accountable.",
    "We optimise to revenue and ROAS, not impressions. Modeled attribution and rigorous spend governance keep your budget pointed where it returns.",
    ["ROAS & CAC targets", "Modeled attribution", "Spend governance", "Profit-based bidding", "Executive ROI reporting"]),
  s("customer-acquisition-campaigns", "Customer Acquisition Campaigns", "Performance Marketing", "performance",
    "New customers at a cost your unit economics love.",
    "From cold audiences to first purchase, we design acquisition systems that scale without blowing up CAC — tested across D2C, SaaS and services.",
    ["Audience & creative testing", "Acquisition funnel design", "LTV / CAC modeling", "Channel diversification", "Scale playbooks"]),
  s("campaign-scaling-optimization", "Campaign Scaling & Optimization", "Performance Marketing", "performance",
    "Take what's working from $1k/day to $20k/day — without breaking it.",
    "Scaling is a different skill from launching. We bring structured scaling frameworks, creative velocity and bid strategy expertise to push winning campaigns hard.",
    ["Scaling readiness audit", "Creative velocity systems", "Bid & budget strategy", "Audience expansion", "Performance guardrails"]),

  // Ads
  s("google-ads-management", "Google Ads Management", "Paid Advertising", "ads",
    "Google Ads run by certified specialists, not interns.",
    "Search, Performance Max, Shopping, YouTube and Demand Gen — managed with daily care, smart structure and creative testing rigour.",
    ["Account audit & restructure", "Keyword & negative strategy", "Performance Max & Shopping", "YouTube & Demand Gen", "Conversion tracking & reporting"]),
  s("meta-ads", "Meta Ads (Facebook & Instagram)", "Paid Advertising", "ads",
    "Creative-led Meta campaigns that scale profitably.",
    "We treat creative as the new targeting. High-velocity ad production, smart account structure and CAPI-grade tracking — all dialled in for ROAS.",
    ["Creative strategy & production", "Account structure & testing", "Conversion API setup", "Audience & lookalike strategy", "Weekly creative refresh"]),
  s("linkedin-ads", "LinkedIn Ads", "Paid Advertising", "ads",
    "B2B pipeline from the only platform where decision-makers live.",
    "Account-based targeting, conversation ads, lead-gen forms and thought-leadership amplification — designed for high-ticket B2B and SaaS.",
    ["ABM & ICP targeting", "Lead-gen form campaigns", "Thought-leadership amplification", "Sales follow-up integration", "Pipeline-level reporting"]),
  s("ppc-advertising", "PPC (Pay-Per-Click) Advertising", "Paid Advertising", "ads",
    "Multi-platform PPC managed as one connected engine.",
    "Google, Bing, Meta, LinkedIn — under one strategy, one dashboard, one team. Less duplication, more learning, better results.",
    ["Cross-platform strategy", "Unified tracking & attribution", "Budget allocation models", "Creative & copy testing", "Single source-of-truth reporting"]),
  s("retargeting-campaigns", "Retargeting Campaigns", "Paid Advertising", "ads",
    "Win back the 95% who didn't convert the first time.",
    "Smart audience segmentation, sequenced creative and frequency caps — so retargeting feels helpful, not creepy, and actually moves revenue.",
    ["Audience segmentation", "Sequenced creative tracks", "Frequency & exclusion logic", "Dynamic product ads", "Revenue attribution"]),
  s("lead-generation-ads", "Lead Generation Ads", "Paid Advertising", "ads",
    "Native lead-gen ads engineered for quality, not just quantity.",
    "We pair native lead forms with qualification logic, instant follow-up and CRM sync so sales actually gets usable leads.",
    ["Native lead form ads", "Qualification questions", "Instant CRM sync", "Speed-to-lead automation", "Sales feedback loops"]),
  s("brand-awareness-campaigns", "Brand Awareness Campaigns", "Paid Advertising", "ads",
    "Make your brand impossible to ignore in your category.",
    "Reach, frequency and message planning that builds memorability — measured with brand lift, share of voice and assisted conversions.",
    ["Reach & frequency planning", "Creative narrative design", "Cross-channel media mix", "Brand lift measurement", "Share-of-voice tracking"]),

  // Social
  s("instagram-marketing", "Instagram Marketing", "Social Media Marketing", "social",
    "Show up daily with content that builds a real audience.",
    "Strategy, content production, reels, community and ads — all aligned to your brand and your buyer.",
    ["Content strategy & calendar", "Reels & static production", "Community management", "Influencer collaborations", "Ads & growth campaigns"]),
  s("facebook-marketing", "Facebook Marketing", "Social Media Marketing", "social",
    "Still the largest paid + organic playground in the world.",
    "We design Facebook strategies that combine community, content and conversion — perfect for local, D2C and community-driven brands.",
    ["Page & group strategy", "Content & video production", "Community management", "Local & national ads", "Performance reporting"]),
  s("linkedin-marketing", "LinkedIn Marketing", "Social Media Marketing", "social",
    "Build a B2B brand that opens doors before sales calls.",
    "Company page strategy, founder thought leadership, employee advocacy and lead-gen — turning LinkedIn into your pipeline engine.",
    ["Company page strategy", "Founder thought leadership", "Employee advocacy", "Content & video", "Lead-gen integration"]),
  s("social-media-management", "Social Media Management", "Social Media Marketing", "social",
    "A senior social team for less than the cost of one hire.",
    "End-to-end management — strategy, content, design, scheduling, community and reporting — on a predictable monthly plan.",
    ["Monthly content calendar", "Design & video production", "Publishing & scheduling", "Community management", "Performance reporting"]),
  s("social-media-strategy", "Social Media Strategy", "Social Media Marketing", "social",
    "Stop posting for the sake of posting.",
    "A documented strategy — audience, pillars, formats, cadence, KPIs — that gives your social work direction and your team confidence.",
    ["Audience & competitor research", "Content pillars & narratives", "Format & cadence plan", "Channel-specific playbooks", "KPI framework"]),
  s("reels-creation", "Reels Creation", "Social Media Marketing", "social",
    "Short-form video built for the scroll, not for an award show.",
    "We script, shoot and edit reels at the pace and quality the algorithm rewards — with hooks, pacing and CTAs that actually convert.",
    ["Concept & script library", "Production & editing", "Hook & CTA testing", "Trend monitoring", "Weekly publishing cadence"]),
  s("content-calendar-planning", "Content Calendar Planning", "Social Media Marketing", "social",
    "Never stare at a blank calendar again.",
    "A 30 / 60 / 90-day rolling calendar with themes, formats and CTAs mapped to your campaigns — built collaboratively with your team.",
    ["Rolling 90-day calendar", "Theme & campaign mapping", "Format diversification", "Approval workflows", "Post-mortem reviews"]),
  s("community-engagement", "Community Engagement", "Social Media Marketing", "social",
    "Turn followers into fans, and fans into customers.",
    "Daily community management with brand voice consistency, fast response times and proactive outreach to creators, partners and customers.",
    ["Daily monitoring & replies", "Voice & tone guidelines", "Creator & partner outreach", "Crisis & escalation playbooks", "Sentiment reporting"]),
  s("influencer-marketing", "Influencer Marketing", "Social Media Marketing", "social",
    "Right creators. Right brief. Real results.",
    "Vetted creator discovery, briefing, contracting and performance tracking across nano, micro and macro tiers.",
    ["Creator discovery & vetting", "Briefing & contracting", "Content approvals", "Performance & ROI tracking", "Long-term ambassador programs"]),
  s("social-media-growth-campaigns", "Social Media Growth Campaigns", "Social Media Marketing", "social",
    "Engineered audience growth with real, engaged followers.",
    "Paid + organic growth sprints designed to add followers that actually engage and buy — no bot accounts, no shortcuts.",
    ["Audience definition", "Hook-driven creative", "Paid amplification", "Collab & cross-promo", "Cohort engagement tracking"]),

  // Branding
  s("content-marketing", "Content Marketing", "Content & Branding", "branding",
    "Content that earns attention, trust and traffic.",
    "Strategy, production and distribution of long-form, video and visual content — engineered to attract your buyer and rank in search.",
    ["Editorial strategy", "Long-form & video production", "SEO-aligned briefs", "Distribution & repurposing", "Performance reporting"]),
  s("linkedin-personal-branding", "LinkedIn Personal Branding", "Content & Branding", "branding",
    "Founders & execs who post inbound their pipeline.",
    "Done-for-you LinkedIn personal branding — voice discovery, content writing, design, posting and engagement — built for serious operators.",
    ["Voice & POV discovery", "Weekly content production", "Carousels & video", "Engagement strategy", "Inbound conversation tracking"]),
  s("thought-leadership-marketing", "Thought Leadership Marketing", "Content & Branding", "branding",
    "Become the brand your category quotes.",
    "Original research, executive bylines, podcasts and earned media built around a sharp, defensible point of view.",
    ["POV development", "Original research & reports", "Executive ghostwriting", "PR & earned media", "Speaking & podcast outreach"]),
  s("brand-identity-development", "Brand Identity Development", "Content & Branding", "branding",
    "A brand system that scales from pitch deck to packaging.",
    "Strategy, naming, logo, type, colour, voice and a usage system your whole team can apply consistently.",
    ["Brand strategy & positioning", "Naming & messaging", "Logo & visual system", "Voice & tone guide", "Brand book & assets"]),
  s("branding-campaigns", "Branding Campaigns", "Content & Branding", "branding",
    "Big-idea campaigns that move perception and pipeline.",
    "Concept, creative, production and rollout for launches, repositions and category-defining moments.",
    ["Campaign concept & idea", "Creative production", "Cross-channel rollout", "PR & influencer amplification", "Brand lift measurement"]),
  s("creative-design", "Creative Design", "Content & Branding", "branding",
    "On-brand design that ships fast.",
    "A senior design pod for ads, social, decks, brochures, web and packaging — with brand guardrails and quick turnarounds.",
    ["Ad & social creative", "Pitch decks & sales collateral", "Web & email design", "Print & packaging", "Brand guardrails"]),
  s("visual-branding", "Visual Branding", "Content & Branding", "branding",
    "A coherent visual language across every touchpoint.",
    "We build and operationalise visual systems so every team — marketing, sales, product — produces work that looks unmistakably like you.",
    ["Visual system design", "Template libraries", "Component & icon kits", "Asset management", "Team enablement"]),

  // Email
  s("email-marketing-campaigns", "Email Marketing Campaigns", "Email Marketing", "email",
    "Email that people actually open — and click.",
    "Strategy, design, copy and deployment for newsletters, launches and lifecycle programs across HubSpot, Mailchimp, Klaviyo and Zoho Campaigns.",
    ["List & segmentation strategy", "Design & copywriting", "Deliverability monitoring", "A/B testing", "Performance reporting"]),
  s("email-automation", "Email Automation", "Email Marketing", "email",
    "Always-on revenue from flows that work while you sleep.",
    "Welcome, nurture, abandoned cart, post-purchase, win-back — designed, built and optimised around your funnel.",
    ["Flow mapping & strategy", "Segmentation & triggers", "Copy & design", "A/B testing & optimisation", "Revenue attribution"]),
  s("promotional-email-campaigns", "Promotional Email Campaigns", "Email Marketing", "email",
    "Launches and offers that drive immediate revenue lifts.",
    "End-to-end promo planning, design, copy, send strategy and reporting — tuned for conversions without burning your list.",
    ["Promo calendar planning", "Offer & creative design", "Segmentation & send strategy", "Deliverability protection", "Revenue reporting"]),
  s("customer-engagement-emails", "Customer Engagement Emails", "Email Marketing", "email",
    "Keep customers active, happy and repeat-buying.",
    "Onboarding, education, milestones, NPS and re-engagement flows that build long-term LTV.",
    ["Lifecycle mapping", "Onboarding & education flows", "Milestone & NPS emails", "Re-engagement programs", "LTV reporting"]),

  // Extras
  s("sem", "SEM (Search Engine Marketing)", "Additional Services", "extras",
    "Combined SEO + paid search strategy from one team.",
    "We run SEO and paid search together — sharing keyword data, landing pages and learnings — so every rupee of search spend compounds.",
    ["Unified keyword strategy", "SEO + PPC coordination", "Shared landing page testing", "Cross-channel reporting", "Search share-of-voice"]),
  s("orm", "Online Reputation Management (ORM)", "Additional Services", "extras",
    "Own what people see when they search your brand.",
    "Review acquisition, response and recovery, plus Google SERP management for branded queries — across India, USA, UK, UAE and beyond.",
    ["Review acquisition systems", "Response & recovery playbooks", "Branded SERP management", "Crisis & escalation", "Monthly reputation reporting"]),
  s("brand-strategy", "Brand Strategy", "Additional Services", "extras",
    "Define what you stand for — and what you don't.",
    "Positioning, value proposition, messaging architecture and customer narrative work that aligns marketing, sales and product.",
    ["Positioning & POV", "Value proposition design", "Messaging architecture", "Customer narrative", "Internal alignment workshops"]),
  s("market-research", "Market Research", "Additional Services", "extras",
    "Decisions backed by what your market actually thinks.",
    "Qualitative interviews, surveys, competitor teardown and category mapping — delivered with crisp, actionable findings.",
    ["Customer & buyer interviews", "Quantitative surveys", "Competitor teardowns", "Category & TAM mapping", "Actionable insight reports"]),
  s("digital-transformation-consulting", "Digital Transformation Consulting", "Additional Services", "extras",
    "Modernise how your business sells, serves and operates.",
    "We help mid-market companies move from spreadsheets and silos to integrated CRM, marketing, support and operations — with adoption that sticks.",
    ["Current state assessment", "Future state & roadmap", "Tooling & vendor selection", "Implementation oversight", "Change management"]),
  s("business-growth-consulting", "Business Growth Consulting", "Additional Services", "extras",
    "Senior operators in your corner, monthly.",
    "Growth strategy, go-to-market, pricing, channels and team design — fractional support from people who've scaled real businesses.",
    ["Growth diagnostic", "GTM & pricing strategy", "Channel & funnel design", "Team & ops design", "Monthly working sessions"]),

  // Industry-specific marketing
  s("legal-marketing", "Legal Marketing", "Industry-Specific Marketing", "industry",
    "Ethical, high-trust marketing built for law firms.",
    "Local SEO, content authority, paid acquisition and ORM tuned to legal compliance and how clients actually pick a lawyer.",
    ["Practice-area landing pages", "Local & national SEO", "Compliant paid campaigns", "Review & reputation systems", "Intake & CRM integration"]),
  s("healthcare-marketing", "Healthcare Marketing", "Industry-Specific Marketing", "industry",
    "Patient growth for clinics, hospitals and wellness brands.",
    "HIPAA-aware, trust-led patient acquisition combining local SEO, reputation, content and paid campaigns.",
    ["Service & doctor pages", "Local SEO & maps dominance", "Review & reputation systems", "Compliant paid acquisition", "Appointment funnel tracking"]),
  s("hospitality-marketing", "Hospitality Marketing", "Industry-Specific Marketing", "industry",
    "Bookings, brand love and repeat guests.",
    "Direct booking strategy, OTA optimisation, social, content and paid for hotels, restaurants and resorts across regions.",
    ["Direct booking funnels", "OTA listing optimisation", "Social & influencer content", "Local & meta search ads", "Guest lifecycle email"]),
  s("ecommerce-marketing", "E-commerce Marketing", "Industry-Specific Marketing", "industry",
    "Scale D2C with paid, SEO and retention loops.",
    "Full-stack e-commerce growth — Meta, Google, Shopping, SEO, email & SMS — focused on contribution margin, not just top-line revenue.",
    ["Meta & Google Shopping ads", "SEO & content programs", "Email & SMS retention", "CRO & product page work", "Contribution margin reporting"]),
  s("saas-marketing", "SaaS Marketing", "Industry-Specific Marketing", "industry",
    "Pipeline, MQLs and product-led growth for software companies.",
    "Category & messaging strategy, SEO, paid, lifecycle and product-led loops — built for SaaS metrics like CAC payback and NRR.",
    ["Category & positioning", "SEO & content engine", "Paid acquisition", "Lifecycle & PLG loops", "RevOps & attribution"]),
  s("real-estate-marketing", "Real Estate Marketing", "Industry-Specific Marketing", "industry",
    "Qualified buyer & investor leads at scale.",
    "Project launches, pre-launch lists, NRI campaigns and channel-partner enablement — for developers, brokers and PropTech.",
    ["Launch & pre-launch campaigns", "NRI & investor targeting", "Project microsites", "CRM & lead routing", "Channel partner enablement"]),
  s("b2b-marketing", "B2B Marketing", "Industry-Specific Marketing", "industry",
    "Account-based marketing & enterprise lead generation.",
    "ICP-led ABM, LinkedIn pipeline programs, content authority and sales enablement — for high-ticket B2B and enterprise sellers.",
    ["ICP & ABM strategy", "LinkedIn pipeline programs", "Content & thought leadership", "Sales enablement", "Pipeline-level reporting"]),
  s("manufacturing-marketing", "Manufacturing Marketing", "Industry-Specific Marketing", "industry",
    "Distributor, dealer & export lead generation.",
    "Multi-language SEO, IndiaMART/Alibaba optimisation, LinkedIn and Google campaigns — proven across India, UAE and global export markets.",
    ["Multi-language SEO", "B2B marketplace optimisation", "LinkedIn & Google campaigns", "Catalogue & spec content", "Distributor lead routing"]),
  s("education-marketing", "Education / EdTech Marketing", "Industry-Specific Marketing", "industry",
    "Enrolment growth and lifecycle marketing.",
    "Admissions funnels, counsellor enablement, paid acquisition and parent/student lifecycle marketing — for schools, colleges and EdTech.",
    ["Admissions funnel design", "Paid acquisition", "Counsellor enablement", "Parent & student lifecycle", "Cohort & ROI reporting"]),
];

export const SERVICE_DETAILS_BY_SLUG: Record<string, ServiceDetail> = Object.fromEntries(
  SERVICE_DETAILS.map((d) => [d.slug, d]),
);

// ---------- Industry detail pages ----------
export type IndustryDetail = {
  slug: string;
  name: string;
  tagline: string;
  intro: string;
  highlights: string[];
};

export const INDUSTRY_DETAILS: IndustryDetail[] = [
  { slug: "legal", name: "Legal", tagline: "Client acquisition for law firms and legal consultants.",
    intro: "We help law firms, boutique practices and legal consultants attract better-fit clients using ethical, compliant marketing — combining local SEO, content authority, paid acquisition and reputation systems.",
    highlights: ["Practice-area landing pages", "Local & national SEO", "Compliant paid campaigns", "Reviews & reputation", "Intake automation"] },
  { slug: "healthcare", name: "Healthcare", tagline: "Patient growth for clinics, hospitals & wellness brands.",
    intro: "From single-specialty clinics to multi-location hospitals, we run patient acquisition programs that balance growth with trust and compliance.",
    highlights: ["Service & doctor pages", "Local SEO & maps", "Reputation systems", "Compliant paid acquisition", "Appointment funnels"] },
  { slug: "hospitality", name: "Hospitality", tagline: "Bookings & brand love for hotels, restaurants & resorts.",
    intro: "We grow direct bookings, optimise OTAs and build the brand layer that turns guests into repeat customers and advocates.",
    highlights: ["Direct booking funnels", "OTA optimisation", "Social & influencer content", "Meta & local search ads", "Guest lifecycle email"] },
  { slug: "ecommerce", name: "E-commerce", tagline: "Scaling D2C brands with paid, SEO and retention loops.",
    intro: "Full-stack growth for D2C — Meta, Google, Shopping, SEO, email & SMS — measured on contribution margin and LTV, not vanity ROAS.",
    highlights: ["Meta & Google Shopping", "SEO & content", "Email & SMS retention", "CRO & PDP work", "Margin reporting"] },
  { slug: "saas", name: "SaaS", tagline: "Pipeline, MQLs and product-led growth for software companies.",
    intro: "Category strategy, SEO, paid, lifecycle and PLG loops — purpose-built for SaaS economics and revenue ops.",
    highlights: ["Category & positioning", "SEO content engine", "Paid acquisition", "Lifecycle & PLG", "Attribution & RevOps"] },
  { slug: "real-estate", name: "Real Estate", tagline: "Qualified buyer & investor leads at scale.",
    intro: "We deliver pre-launch lists, NRI campaigns, project microsites and channel-partner enablement for developers, brokers and PropTech players.",
    highlights: ["Launch campaigns", "NRI & investor targeting", "Project microsites", "CRM & routing", "Channel enablement"] },
  { slug: "b2b", name: "B2B", tagline: "Account-based marketing & enterprise lead generation.",
    intro: "ICP-led ABM, LinkedIn pipeline programs, content authority and sales enablement for high-ticket B2B sellers.",
    highlights: ["ICP & ABM", "LinkedIn pipeline", "Thought leadership", "Sales enablement", "Pipeline reporting"] },
  { slug: "manufacturing", name: "Manufacturing", tagline: "Distributor, dealer & export lead generation.",
    intro: "Multi-language SEO, B2B marketplace optimisation and global lead-gen — proven across India, the Gulf and export markets.",
    highlights: ["Multi-language SEO", "IndiaMART / Alibaba", "LinkedIn & Google", "Catalogue content", "Distributor routing"] },
  { slug: "education", name: "Education / EdTech", tagline: "Enrolment growth and lifecycle marketing.",
    intro: "Admissions funnels, counsellor enablement and parent/student lifecycle marketing for schools, colleges and EdTech brands.",
    highlights: ["Admissions funnels", "Paid acquisition", "Counsellor enablement", "Parent & student lifecycle", "Cohort ROI"] },
];

export const INDUSTRY_DETAILS_BY_SLUG: Record<string, IndustryDetail> = Object.fromEntries(
  INDUSTRY_DETAILS.map((d) => [d.slug, d]),
);

// Map raw service item names (as they appear in SERVICE_CATEGORIES.items) → detail slug
export const SERVICE_NAME_TO_SLUG: Record<string, string> = Object.fromEntries(
  SERVICE_DETAILS.map((d) => [d.name, d.slug]),
);

